add solution for 6-module 5-task
js-tasks-ru/htmlcss-20211125_zvykkk pull request #16
Opened 2021-12-19 14:41 UTC by zvykkk

2021-12-19 14:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-19 18:55 UTC, GSemikozov requested changes

2021-12-19 18:55 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details[open] .marker {
селекторы тегов не используем, для этого элемента есть свой класс

2021-12-19 18:55 UTC, GSemikozov commented on 05-lection3/01-tooltip/index.html
> +                    <use href="././assets/icons/sprite.svg#help"></use>
././ -> ./

2021-12-20 12:27 UTC, zvykkk commented on 05-lection3/01-tooltip/index.html
> +                    <use href="././assets/icons/sprite.svg#help"></use>
поправила)

2021-12-20 12:35 UTC, zvykkk commented on 03-lection1/02-accordion/accordion.css
> +details[open] .marker {
поправила)

2021-12-20 12:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-24 12:54 UTC, GSemikozov approved these changes

2021-12-24 13:13 UTC, merged