add solution for 9-module 1-task
js-tasks-ru/htmlcss-20211125_zvykkk pull request #22
Opened 2021-12-26 16:59 UTC by zvykkk

2021-12-26 17:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-26 19:22 UTC, GSemikozov requested changes

2021-12-26 19:22 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__body {
это лишний враппер, стили этого класса надо перенести на .burger-menu

2021-12-26 19:22 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__control-open {
поскольку вот эта кнопка - это на самом деле не часть меню,  триггером может быть по сути любой элемент, в нашем случае - это будет элемент хедера кнопка бургера (кнопка вызова мобильного меню). А на странице с примером - можно использовать обычную кнопку

2021-12-27 06:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-27 07:09 UTC, zvykkk commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__body {
поправила)

2021-12-27 07:57 UTC, zvykkk commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu__control-open {
понятно, поправила)

2021-12-27 08:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-27 20:03 UTC, GSemikozov approved these changes

2021-12-27 20:03 UTC, merged