add solution for 4-module 2-task
js-tasks-ru/htmlcss-20211125_zvykkk pull request #7
Opened 2021-12-12 10:22 UTC by zvykkk

2021-12-12 10:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-13 15:23 UTC, GSemikozov requested changes

2021-12-13 15:23 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-basis: 257px;
здесь лучше не ограничивать

2021-12-13 15:23 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-basis: 257px;
а просто добавить еще один модификатор для skeleton__item

2021-12-13 15:23 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-basis: 257px;
и тогда по стилям этот элемент совпадет с .skeleton__body - можно переделать в один, например .skeleton__box

2021-12-13 15:23 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.width {
можификаторы задаем как модификаторы а не как блоки) .skeleton__item_medium и тд

2021-12-14 06:32 UTC, zvykkk commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-basis: 257px;
понятно, исправила)

2021-12-14 06:32 UTC, zvykkk commented on 04-lection2/02-skeleton/skeleton.css
> +.width {
исправила

2021-12-14 19:53 UTC, GSemikozov approved these changes

2021-12-14 19:53 UTC, merged